[platformio]
default_envs = esp32_ble_test

[env:esp32_ble_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
    -DMAJN_BLE_ONLY_TEST=1
lib_deps =
    bblanchon/ArduinoJson@^7.0.0

[env:esp32_full_hw]
platform = espressif32
board = esp32dev
board_build.partitions = partitions_8mb_ota.csv
board_upload.flash_size = 8MB
framework = arduino
monitor_speed = 115200
build_flags = 
    -DMAJN_FULL_HW=1
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
