[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    tzapu/WiFiManager

; OTA 업로드를 사용할 때 활성화 (처음에는 시리얼 업로드 후, 나중에 Wi-Fi 업로드 시 주석 해제하여 사용)
; upload_protocol = espota
; upload_port = 192.168.0.X ; ESP32의 IP 주소 기입
